#define FORWARD     1
#define RIGHT       2
#define LEFT        3
#define BACKWARD    4

#define ULTRALEFT   0
#define ULTRARIGHT  180
#define ULTRAMIDDLE 90

#define ULTRATURNSCALE 1000
#define ULTRATURNMIN 75
#define ULTRATURNANGLE 30

#define LINELEFT    1
#define LINERIGHT   2

#define FRONTBEACONSENSOR A5
#define BACKBEACONSENSOR A4
#define BEACONLOWERTHRESHOLD 45
#define BEACONUPPERTHRESHOLD 700
